---                                                                                                                                                                                                                  
- name : cosbench Install
  hosts: cosbench
  gather_facts: true
  become: true
                                                                                                                                                                                                                     
  tasks:
  - name: remove firewall
    yum:
      name: firewalld
      state: absent
  - name: Install package
    yum:
      name: '{{ item }}'
      state: present
    with_items:
      - wget
      - java
      - unzip
      - nc
      - java-1.7.0-openjdk
  - name: Create Download Folder
    file:
      path: /root/benchmark/download
      state: directory
  - name: Package Download
    get_url:
      url: ftp://172.18.0.18/pub/centos/bmtools/cosbench042.zip
      dest: /root/benchmark/download
  - name: Create cosbench Folder
    file:
      path: /root/benchmark/cosbench
      state: directory
  - name: UnZip cosbench Package
    unarchive:
     src: /root/benchmark/download/cosbench042.zip
     dest: /root/benchmark/cosbench/
     remote_src: True
  - name: Add executable permission
    shell: "chmod +x *.sh"
    args:
      chdir: /root/benchmark/cosbench/0.4.2.c4/
