---
- name : cosbench Process Start
  hosts: cosbench
  gather_facts: true
  become: true

  tasks:
#  - name: Change cosbench driver IP
#    ansible.builtin.lineinfile:
#      path: /root/benchmark/cosbench/start-driver.sh
#      regexp: 127.0.0.1
#      line: ip='{{ ansible_eth0.ipv4.address }}'
  - name: Started Cosbench Driver
    ansible.builtin.shell: |
      ./stop-driver.sh
      ./start-driver.sh 
#      ./start-driver.sh "{{ hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}"
    args:
      chdir: /root/benchmark/cosbench/0.4.2.c4/
