---
- name : check Process
  hosts: all
  gather_facts: true
  become: true

  tasks:
  - name: Install package
    yum:
      name: '{{ item }}'
      state: present
    with_items:
      - wget
  - name: Started Cosbench Driver
    ansible.builtin.shell: |
      ntpq -p
#      cat /etc/resolv.conf | grep nameserver
#      cat /etc/ntp.conf | grep server
#      ls /etc/yum.repos.d/ | grep repo
